package hayride:morph@0.0.3;

interface spawn {
    use wasi:io/streams@0.2.0.{input-stream, output-stream};
    use wasi:io/error@0.2.0.{error};

    exec: func(name: string, args: output-stream) -> result<input-stream, error>;
}