package hayride:core@0.0.53;

interface api {
    use hayride:silo/threads@0.0.53.{thread-metadata, thread-status};

    record cast {
        name: string,
        function: string,
        args: list<string>,
    }

    record sessions {
        sessions: list<thread-metadata>,
    }

    variant request-data {
        unknown,
        cast(cast),
        session-id(string),
    }

    variant response-data {
        unknown,
        sessions(thread-metadata),
        session-id(string),
        session-status(thread-status),
    }

    record request {
        data: request-data,
        metadata: list<tuple<string, string>>,
    }

    record response {
        data: response-data,
        error: string,

        // Cursor for pagination
        next: string,
        prev: string,
    }
}

interface ai-api {
    use hayride:ai/types@0.0.53.{message};

    variant data {
        unknown,
        messages(list<message>),
    }

    record request {
        data: data,
        metadata: list<tuple<string, string>>,
    }

    record response {
        data: data,
        error: string,

        // Cursor for pagination
        next: string,
        prev: string,
    }
}
