package hayride:core@0.0.55;

interface api {
    use hayride:silo/threads@0.0.55.{thread-metadata, thread-status};

    record cast {
        name: string,
        function: string,
        args: list<string>,
    }

    record morph {
        pkg: string,
        name: string,
        version: string,
        data: list<u8>,
    }

    variant request-data {
        unknown,
        cast(cast),
        session-id(string),
        publish(morph),
    }

    variant response-data {
        unknown,
        sessions(list<thread-metadata>),
        session-id(string),
        session-status(thread-status),
    }

    record request {
        data: request-data,
        metadata: list<tuple<string, string>>,
    }

    record response {
        data: response-data,
        error: string,

        // Cursor for pagination
        next: string,
        prev: string,
    }
}

interface ai-api {
    use hayride:ai/types@0.0.55.{message};

    variant request-data {
        unknown,
        messages(list<message>),
    }

    variant response-data {
        unknown,
        messages(list<message>),
        path(string),
    }

    record request {
        data: request-data,
        metadata: list<tuple<string, string>>,
    }

    record response {
        data: response-data,
        error: string,

        // Cursor for pagination
        next: string,
        prev: string,
    }
}
