package hayride:core@0.0.47;

interface types {
    record logging {
        enabled: bool,
        level: string,
        file: string
    }

    record http {
        address: string
    }

    record websocket {
        address: string
    }

    record server {
        bin: string,
        logging: logging,
        http: http,
    }

    record cli {
        bin: string,
        logging: logging,
    }

    record ai {
        bin: string,
        logging: logging,
        http: http,
        websocket: websocket,
    }

    record ui {
        bin: string,
        logging: logging,
        http: http,
    }

    record config {
        version: string,
        license: string,
        core: list<morph>,
        features: list<feature>,
    }

    enum error-code {
        set-failed,
        get-failed,
        config-not-set,
        unknown
    }

    variant morph {
        cli(cli),
        server(server),
    }

    variant feature {
        ai(ai),
        ui(ui),
    }
    
    resource error {
        /// Return the error code.
        code: func() -> error-code;

        /// Errors can propagated with backend specific status through a string value.
        data: func() -> string;
    }
}

interface config {
    use types.{config, error};
    get: func() -> result<config, error>;
    set: func(config: config) -> result<_, error>;
}
