package hayride:ai@0.0.49;

interface agent {
    use types.{message};
    use wasi:io/streams@0.2.0.{output-stream};

    enum error-code {
        invoke-error,
        unknown
    }

    resource error {
        /// return the error code.
        code: func() -> error-code;
        /// errors can propagated with backend specific status through a string value.
        data: func() -> string;
    }

    resource agent {
        constructor();
        invoke: func(messages: list<message>) -> result<list<message>, error>;
        invoke-stream: func(messages: list<message>, writer: output-stream) -> result<_,error>;
    }
}
