package hayride:ai@0.0.40;

interface context {
    use types.{message};
    use wasi:io/streams@0.2.0.{output-stream};
    use tensor-stream.{tensor-stream};

    enum error-code {
        unexpected-message-type,
        write-error,
        message-not-found,
        pipe-error,
        unknown
    }

    resource error {
        /// return the error code.
        code: func() -> error-code;
        /// errors can propagated with backend specific status through a string value.
        data: func() -> string;
    }


    resource context {
        constructor();
        write: func(messages: list<message>) -> result<_, error>;
        messages: func() -> result<list<message>, error>;
        next: func() -> result<message, error>;
    }
} 



