package hayride:ai@0.0.51;

interface model {
    use inference-stream.{graph-execution-context-stream};
    use types.{message};
    use context.{context};

    enum error-code {
        context-error,
        context-encode,
        context-decode,
        compute-error,
        unknown
    }

    resource error {
        /// return the error code.
        code: func() -> error-code;
        /// errors can propagated with backend specific status through a string value.
        data: func() -> string;
    }

    resource model {
        constructor();
        // todo: add options to compute so we can set model specific options
        compute: func(graph: graph-execution-context-stream, messages: list<message>) -> result<message,error>;    
    }
}



