package hayride:ai@0.0.61;

interface types {
    use hayride:mcp/types@0.0.61.{tool-schema, call-tool-params, call-tool-result};

    enum role {
        user,
        assistant,
        system,
        tool,
        unknown
    }

    record text-content {
        text: string, 
        content-type: string
    }
    
    variant content {
        none,
        text(text-content),
        tool-schema(tool-schema),
        tool-input(call-tool-params),
        tool-output(call-tool-result),
    }

    record message {
        role: role,
        content: list<content>
    }
}
