package hayride:ai@0.0.54;

world imports {
    include wasi:nn/ml@0.2.0-rc-2024-10-28;
    // hayride streaming extension
    import tensor-stream;
    import inference-stream;
    import graph-stream;

    import agents;
    import model;
    import model-repository;
    import rag;
}

world exports {
    export agents;
    export model;
}
