package hayride:ai@0.0.2;

world imports {
    import wasi:nn/tensor@0.2.0-rc-2024-08-19;
    import wasi:nn/graph@0.2.0-rc-2024-08-19;
    import wasi:nn/inference@0.2.0-rc-2024-08-19;
    import wasi:nn/errors@0.2.0-rc-2024-08-19;
}