package hayride:ai@0.0.22;

world imports {
    import wasi:nn/tensor@0.2.0-rc-2024-10-28;
    import wasi:nn/graph@0.2.0-rc-2024-10-28;
    import wasi:nn/inference@0.2.0-rc-2024-10-28;
    import wasi:nn/errors@0.2.0-rc-2024-10-28;
    // hayride streaming extension
    import tensor-stream;
    import inference-stream;
    import graph-stream;
}