package hayride:wac@0.0.37;

interface types {
    enum error-code {
        file-not-found,
        resolve-failed,
        compose-failed,
        encode-failed,
        unknown
    }

    resource error {
        /// Return the error code.
        code: func() -> error-code;

        /// Errors can propagated with backend specific status through a string value.
        data: func() -> string;
    }
}
