package hayride:wac@0.0.57;

interface wac {
    use types.{error};
    compose: func(contents: string) -> result<list<u8>, error>;
    plug: func(socket-pkg: string, plug-pkgs: list<string>) -> result<list<u8>, error>;
}
