package hayride:broom@0.0.1;

world wasip2-proposals {
    import wasi:http/types@0.2.2;
    import wasi:http/outgoing-handler@0.2.2;
    include wasi:nn/ml@0.2.0-rc-2024-08-19;
}

world wasip2 {
    include wasip2-proposals;
    // WASI imports/exports are dependent on the compile toolchain. 
    // These are common imports by wasip2 and compilers may
    // opt in to include these are targets at comp time. 
    import wasi:clocks/wall-clock@0.2.2;
    import wasi:clocks/monotonic-clock@0.2.2;
    import wasi:random/random@0.2.2;
    import wasi:io/streams@0.2.2;
    import wasi:filesystem/types@0.2.2;
    import wasi:filesystem/preopens@0.2.2;
    import wasi:cli/stdout@0.2.2;
    import wasi:cli/stderr@0.2.2;  
    import wasi:cli/stdin@0.2.2;
    import wasi:cli/environment@0.2.2;
    export wasi:cli/run@0.2.2;
}

world llm {
    include wasip2;
}