package hayride:silo@0.0.30;

interface threads {
      /// system error numbers
      type err-no = u32;

      spawn: func(path: string, function: string, args: list<string>) -> result<s32, err-no>;
      wait: func(thread-id: u32) -> result<list<u8>, err-no>;
}
